// AUTO-GENERATED by scripts/build-guided-registry.mts. Do not edit the
// list by hand; add lesson files to guided-lessons/ and re-run the script.
import type { GuidedLesson } from "./guided-lesson-types";
import { ESTIMATION_AND_ROUNDING } from "./guided-lessons/apply-estimation-strategies-and-rounding-rules-to-real-world-problems";
import { ARITHMETIC_RATIONAL_NUMBERS } from "./guided-lessons/arithmetic-rational-numbers";
import { CALCULATE_GEOMETRIC_QUANTITIES } from "./guided-lessons/calculate-geometric-quantities";
import { COMPARE_ORDER_RATIONAL_NUMBERS } from "./guided-lessons/compare-order-rational-numbers";
import { CONVERT_DECIMALS_FRACTIONS_PERCENTS } from "./guided-lessons/convert-among-decimals-fractions-percents";
import { CONVERT_STANDARD_METRIC_UNITS } from "./guided-lessons/convert-within-and-between-standard-and-metric-units";
import { TABLES_CHARTS_GRAPHS_STATISTICS } from "./guided-lessons/evaluate-information-in-tables-charts-and-graphs-using-statistics";
import { RELATIONSHIP_BETWEEN_VARIABLES } from "./guided-lessons/explain-the-relationship-between-variables";
import { INTERPRET_TABLES_CHARTS_GRAPHS } from "./guided-lessons/interpret-relevant-information-from-tables-charts-and-graphs";
import { SOLVE_EQUATIONS_IN_ONE_VARIABLE } from "./guided-lessons/solve-equations-in-one-variable";
import { REAL_WORLD_PERCENT_PROBLEMS } from "./guided-lessons/solve-real-world-problems-involving-percents";
import { PROPORTIONS_RATIOS_RATES } from "./guided-lessons/solve-real-world-problems-involving-proportions-ratios-and-rates-of-change";
import { TRANSLATE_EXPRESSIONS_EQUATIONS_INEQUALITIES } from "./guided-lessons/translate-phrases-and-sentences-into-expressions-equations-and-inequalities";

/**
 * Registry of skills converted to the guided lesson format. Skills not listed
 * here fall back to the flat LessonContent renderer, so conversion ships one
 * skill at a time.
 */
const GUIDED_LESSONS: GuidedLesson[] = [
  ESTIMATION_AND_ROUNDING,
  ARITHMETIC_RATIONAL_NUMBERS,
  CALCULATE_GEOMETRIC_QUANTITIES,
  COMPARE_ORDER_RATIONAL_NUMBERS,
  CONVERT_DECIMALS_FRACTIONS_PERCENTS,
  CONVERT_STANDARD_METRIC_UNITS,
  TABLES_CHARTS_GRAPHS_STATISTICS,
  RELATIONSHIP_BETWEEN_VARIABLES,
  INTERPRET_TABLES_CHARTS_GRAPHS,
  SOLVE_EQUATIONS_IN_ONE_VARIABLE,
  REAL_WORLD_PERCENT_PROBLEMS,
  PROPORTIONS_RATIOS_RATES,
  TRANSLATE_EXPRESSIONS_EQUATIONS_INEQUALITIES,
];

export function getGuidedLesson(
  section: string,
  topic: string,
  slug: string,
): GuidedLesson | undefined {
  return GUIDED_LESSONS.find(
    (l) => l.section === section && l.topic === topic && l.slug === slug,
  );
}

export function guidedLessonCount(): number {
  return GUIDED_LESSONS.length;
}
