// AUTO-GENERATED by scripts/build-guided-registry.mts. Do not edit the
// list by hand; add lesson files to guided-lessons/ and re-run the script.
import type { GuidedLesson } from "./guided-lesson-types";
import { MENDEL_LAWS_INHERITANCE } from "./guided-lessons/apply-concepts-underlying-mendel-s-laws-of-inheritance";
import { ESTIMATION_AND_ROUNDING } from "./guided-lessons/apply-estimation-strategies-and-rounding-rules-to-real-world-problems";
import { APPLY_LOGIC_EVIDENCE_SCIENTIFIC_EXPLANATIONS } from "./guided-lessons/apply-logic-and-evidence-to-scientific-explanations";
import { SCIENTIFIC_METHOD_INVESTIGATION } from "./guided-lessons/apply-the-scientific-method-to-interpret-a-scientific-investigation";
import { ARITHMETIC_RATIONAL_NUMBERS } from "./guided-lessons/arithmetic-rational-numbers";
import { CALCULATE_GEOMETRIC_QUANTITIES } from "./guided-lessons/calculate-geometric-quantities";
import { CARDIOVASCULAR_SYSTEM } from "./guided-lessons/cardiovascular-system";
import { COMPARE_ORDER_RATIONAL_NUMBERS } from "./guided-lessons/compare-order-rational-numbers";
import { CONVERT_DECIMALS_FRACTIONS_PERCENTS } from "./guided-lessons/convert-among-decimals-fractions-percents";
import { CONVERT_STANDARD_METRIC_UNITS } from "./guided-lessons/convert-within-and-between-standard-and-metric-units";
import { GENERAL_ORIENTATION_HUMAN_ANATOMY } from "./guided-lessons/demonstrate-knowledge-of-the-general-orientation-of-human-anatomy";
import { CELL_STRUCTURE_FUNCTION_ORGANIZATION } from "./guided-lessons/describe-cell-structure-function-and-organization";
import { DESCRIBE_CHEMICAL_REACTIONS } from "./guided-lessons/describe-chemical-reactions";
import { GENETIC_MATERIAL_AND_PROTEIN_STRUCTURE } from "./guided-lessons/describe-the-relationship-between-genetic-material-and-protein-structure";
import { MICROORGANISMS_IN_DISEASE } from "./guided-lessons/describe-the-role-of-microorganisms-in-disease";
import { BASIC_MACROMOLECULES } from "./guided-lessons/describe-the-structure-and-function-of-the-basic-macromolecules-in-a-biological-system";
import { ENDOCRINE_SYSTEM } from "./guided-lessons/endocrine-system";
import { TABLES_CHARTS_GRAPHS_STATISTICS } from "./guided-lessons/evaluate-information-in-tables-charts-and-graphs-using-statistics";
import { PHYSICAL_PROPERTIES_CHANGES_MATTER } from "./guided-lessons/explain-physical-properties-and-changes-of-matter";
import { RELATIONSHIP_BETWEEN_VARIABLES } from "./guided-lessons/explain-the-relationship-between-variables";
import { GASTROINTESTINAL_SYSTEM } from "./guided-lessons/gastrointestinal-system";
import { GENITOURINARY_SYSTEM } from "./guided-lessons/genitourinary-system";
import { IMMUNE_SYSTEM } from "./guided-lessons/immune-system";
import { INTEGUMENTARY_SYSTEM } from "./guided-lessons/integumentary-system";
import { INTERPRET_TABLES_CHARTS_GRAPHS } from "./guided-lessons/interpret-relevant-information-from-tables-charts-and-graphs";
import { NEUROMUSCULAR_SYSTEM } from "./guided-lessons/neuromuscular-system";
import { PREDICT_RELATIONSHIPS } from "./guided-lessons/predict-relationships-among-events-objects-and-processes";
import { RECOGNIZE_BASIC_ATOMIC_STRUCTURE } from "./guided-lessons/recognize-basic-atomic-structure";
import { REPRODUCTIVE_SYSTEM } from "./guided-lessons/reproductive-system";
import { RESPIRATORY_SYSTEM } from "./guided-lessons/respiratory-system";
import { SKELETAL_SYSTEM } from "./guided-lessons/skeletal-system";
import { SOLVE_EQUATIONS_IN_ONE_VARIABLE } from "./guided-lessons/solve-equations-in-one-variable";
import { REAL_WORLD_PERCENT_PROBLEMS } from "./guided-lessons/solve-real-world-problems-involving-percents";
import { PROPORTIONS_RATIOS_RATES } from "./guided-lessons/solve-real-world-problems-involving-proportions-ratios-and-rates-of-change";
import { TRANSLATE_EXPRESSIONS_EQUATIONS_INEQUALITIES } from "./guided-lessons/translate-phrases-and-sentences-into-expressions-equations-and-inequalities";
import { PROPERTIES_OF_SOLUTIONS } from "./guided-lessons/understand-properties-of-solutions";
import { BASIC_SCIENTIFIC_MEASUREMENTS_TOOLS } from "./guided-lessons/use-basic-scientific-measurements-and-measurement-tools";

/**
 * Registry of skills converted to the guided lesson format. Skills not listed
 * here fall back to the flat LessonContent renderer, so conversion ships one
 * skill at a time.
 */
const GUIDED_LESSONS: GuidedLesson[] = [
  MENDEL_LAWS_INHERITANCE,
  ESTIMATION_AND_ROUNDING,
  APPLY_LOGIC_EVIDENCE_SCIENTIFIC_EXPLANATIONS,
  SCIENTIFIC_METHOD_INVESTIGATION,
  ARITHMETIC_RATIONAL_NUMBERS,
  CALCULATE_GEOMETRIC_QUANTITIES,
  CARDIOVASCULAR_SYSTEM,
  COMPARE_ORDER_RATIONAL_NUMBERS,
  CONVERT_DECIMALS_FRACTIONS_PERCENTS,
  CONVERT_STANDARD_METRIC_UNITS,
  GENERAL_ORIENTATION_HUMAN_ANATOMY,
  CELL_STRUCTURE_FUNCTION_ORGANIZATION,
  DESCRIBE_CHEMICAL_REACTIONS,
  GENETIC_MATERIAL_AND_PROTEIN_STRUCTURE,
  MICROORGANISMS_IN_DISEASE,
  BASIC_MACROMOLECULES,
  ENDOCRINE_SYSTEM,
  TABLES_CHARTS_GRAPHS_STATISTICS,
  PHYSICAL_PROPERTIES_CHANGES_MATTER,
  RELATIONSHIP_BETWEEN_VARIABLES,
  GASTROINTESTINAL_SYSTEM,
  GENITOURINARY_SYSTEM,
  IMMUNE_SYSTEM,
  INTEGUMENTARY_SYSTEM,
  INTERPRET_TABLES_CHARTS_GRAPHS,
  NEUROMUSCULAR_SYSTEM,
  PREDICT_RELATIONSHIPS,
  RECOGNIZE_BASIC_ATOMIC_STRUCTURE,
  REPRODUCTIVE_SYSTEM,
  RESPIRATORY_SYSTEM,
  SKELETAL_SYSTEM,
  SOLVE_EQUATIONS_IN_ONE_VARIABLE,
  REAL_WORLD_PERCENT_PROBLEMS,
  PROPORTIONS_RATIOS_RATES,
  TRANSLATE_EXPRESSIONS_EQUATIONS_INEQUALITIES,
  PROPERTIES_OF_SOLUTIONS,
  BASIC_SCIENTIFIC_MEASUREMENTS_TOOLS,
];

export function getGuidedLesson(
  section: string,
  topic: string,
  slug: string,
): GuidedLesson | undefined {
  return GUIDED_LESSONS.find(
    (l) => l.section === section && l.topic === topic && l.slug === slug,
  );
}

export function guidedLessonCount(): number {
  return GUIDED_LESSONS.length;
}
