// AUTO-GENERATED by scripts/build-guided-registry.mts. Do not edit the
// list by hand; add lesson files to guided-lessons/ and re-run the script.
import type { GuidedLesson } from "./guided-lesson-types";
import { ANALYZE_TYPES_OF_WRITING } from "./guided-lessons/analyze-types-of-writing";
import { MENDEL_LAWS_INHERITANCE } from "./guided-lessons/apply-concepts-underlying-mendel-s-laws-of-inheritance";
import { ESTIMATION_AND_ROUNDING } from "./guided-lessons/apply-estimation-strategies-and-rounding-rules-to-real-world-problems";
import { APPLY_LOGIC_EVIDENCE_SCIENTIFIC_EXPLANATIONS } from "./guided-lessons/apply-logic-and-evidence-to-scientific-explanations";
import { SCIENTIFIC_METHOD_INVESTIGATION } from "./guided-lessons/apply-the-scientific-method-to-interpret-a-scientific-investigation";
import { CALCULATE_GEOMETRIC_QUANTITIES } from "./guided-lessons/calculate-geometric-quantities";
import { CARDIOVASCULAR_SYSTEM } from "./guided-lessons/cardiovascular-system";
import { COMPARE_CONTRAST_THEMES } from "./guided-lessons/compare-and-contrast-the-themes-expressed-in-one-or-more-texts";
import { COMPARE_ORDER_RATIONAL_NUMBERS } from "./guided-lessons/compare-order-rational-numbers";
import { CONVERT_DECIMALS_FRACTIONS_PERCENTS } from "./guided-lessons/convert-among-decimals-fractions-percents";
import { CONVERT_STANDARD_METRIC_UNITS } from "./guided-lessons/convert-within-and-between-standard-and-metric-units";
import { COMPREHENSION_WRITTEN_DIRECTIONS } from "./guided-lessons/demonstrate-comprehension-of-written-directions";
import { GENERAL_ORIENTATION_HUMAN_ANATOMY } from "./guided-lessons/demonstrate-knowledge-of-the-general-orientation-of-human-anatomy";
import { CELL_STRUCTURE_FUNCTION_ORGANIZATION } from "./guided-lessons/describe-cell-structure-function-and-organization";
import { DESCRIBE_CHEMICAL_REACTIONS } from "./guided-lessons/describe-chemical-reactions";
import { GENETIC_MATERIAL_AND_PROTEIN_STRUCTURE } from "./guided-lessons/describe-the-relationship-between-genetic-material-and-protein-structure";
import { MICROORGANISMS_IN_DISEASE } from "./guided-lessons/describe-the-role-of-microorganisms-in-disease";
import { BASIC_MACROMOLECULES } from "./guided-lessons/describe-the-structure-and-function-of-the-basic-macromolecules-in-a-biological-system";
import { DISTINGUISH_FACT_AND_OPINION } from "./guided-lessons/distinguish-between-fact-and-opinion";
import { ENDOCRINE_SYSTEM } from "./guided-lessons/endocrine-system";
import { EVALUATE_AN_ARGUMENT } from "./guided-lessons/evaluate-an-argument";
import { EVALUATE_INTEGRATE_DATA_MULTIPLE_SOURCES } from "./guided-lessons/evaluate-and-integrate-data-from-multiple-sources-across-various-formats";
import { TABLES_CHARTS_GRAPHS_STATISTICS } from "./guided-lessons/evaluate-information-in-tables-charts-and-graphs-using-statistics";
import { EVALUATE_AUTHORS_POINT_OF_VIEW } from "./guided-lessons/evaluate-the-author-s-point-of-view-or-perspective-in-a-given-text";
import { EVALUATE_AUTHORS_PURPOSE } from "./guided-lessons/evaluate-the-author-s-purpose-in-a-given-text";
import { PHYSICAL_PROPERTIES_CHANGES_MATTER } from "./guided-lessons/explain-physical-properties-and-changes-of-matter";
import { RELATIONSHIP_BETWEEN_VARIABLES } from "./guided-lessons/explain-the-relationship-between-variables";
import { GASTROINTESTINAL_SYSTEM } from "./guided-lessons/gastrointestinal-system";
import { GENITOURINARY_SYSTEM } from "./guided-lessons/genitourinary-system";
import { IDENTIFY_BIASES_AND_STEREOTYPES } from "./guided-lessons/identify-biases-and-stereotypes";
import { IDENTIFY_INFORMATION_FROM_A_GRAPHIC } from "./guided-lessons/identify-information-from-a-graphic";
import { IDENTIFY_INFORMATION_PRINTED_COMMUNICATION } from "./guided-lessons/identify-information-from-a-printed-communication";
import { IDENTIFY_PRIMARY_SOURCES } from "./guided-lessons/identify-primary-sources";
import { TOPIC_MAIN_IDEA_SUPPORTING_DETAILS } from "./guided-lessons/identify-the-topic-main-idea-and-supporting-details";
import { IMMUNE_SYSTEM } from "./guided-lessons/immune-system";
import { INFER_LOGICAL_CONCLUSIONS } from "./guided-lessons/infer-logical-conclusions-from-a-text";
import { INTEGUMENTARY_SYSTEM } from "./guided-lessons/integumentary-system";
import { INTERPRET_EVENTS_SEQUENCE } from "./guided-lessons/interpret-events-in-a-sequence";
import { INTERPRET_TABLES_CHARTS_GRAPHS } from "./guided-lessons/interpret-relevant-information-from-tables-charts-and-graphs";
import { INTERPRET_WORDS_PHRASES_CONTEXT } from "./guided-lessons/interpret-the-meaning-of-words-and-phrases-using-context";
import { LOCATE_SPECIFIC_INFORMATION } from "./guided-lessons/locate-specific-information-in-a-text";
import { NEUROMUSCULAR_SYSTEM } from "./guided-lessons/neuromuscular-system";
import { ARITHMETIC_RATIONAL_NUMBERS } from "./guided-lessons/perform-arithmetic-operations-with-rational-numbers-whole-numbers-decimals-fractions";
import { PREDICT_RELATIONSHIPS } from "./guided-lessons/predict-relationships-among-events-objects-and-processes";
import { RECOGNIZE_BASIC_ATOMIC_STRUCTURE } from "./guided-lessons/recognize-basic-atomic-structure";
import { RECOGNIZE_TEXT_STRUCTURE } from "./guided-lessons/recognize-text-structure";
import { REPRODUCTIVE_SYSTEM } from "./guided-lessons/reproductive-system";
import { RESPIRATORY_SYSTEM } from "./guided-lessons/respiratory-system";
import { SKELETAL_SYSTEM } from "./guided-lessons/skeletal-system";
import { SOLVE_EQUATIONS_IN_ONE_VARIABLE } from "./guided-lessons/solve-equations-in-one-variable";
import { REAL_WORLD_PERCENT_PROBLEMS } from "./guided-lessons/solve-real-world-problems-involving-percents";
import { PROPORTIONS_RATIOS_RATES } from "./guided-lessons/solve-real-world-problems-involving-proportions-ratios-and-rates-of-change";
import { SUMMARIZE_MULTI_PARAGRAPH_TEXT } from "./guided-lessons/summarize-a-multi-paragraph-text";
import { TRANSLATE_EXPRESSIONS_EQUATIONS_INEQUALITIES } from "./guided-lessons/translate-phrases-and-sentences-into-expressions-equations-and-inequalities";
import { PROPERTIES_OF_SOLUTIONS } from "./guided-lessons/understand-properties-of-solutions";
import { BASIC_SCIENTIFIC_MEASUREMENTS_TOOLS } from "./guided-lessons/use-basic-scientific-measurements-and-measurement-tools";
import { USE_DICTIONARY_AND_LIBRARY_ENTRIES } from "./guided-lessons/use-dictionary-and-library-entries";
import { EVIDENCE_PREDICTIONS_INFERENCES_CONCLUSIONS } from "./guided-lessons/use-evidence-from-the-text-to-make-predictions-inferences-and-draw-conclusions";

/**
 * Registry of skills converted to the guided lesson format. Skills not listed
 * here fall back to the flat LessonContent renderer, so conversion ships one
 * skill at a time.
 */
const GUIDED_LESSONS: GuidedLesson[] = [
  ANALYZE_TYPES_OF_WRITING,
  MENDEL_LAWS_INHERITANCE,
  ESTIMATION_AND_ROUNDING,
  APPLY_LOGIC_EVIDENCE_SCIENTIFIC_EXPLANATIONS,
  SCIENTIFIC_METHOD_INVESTIGATION,
  CALCULATE_GEOMETRIC_QUANTITIES,
  CARDIOVASCULAR_SYSTEM,
  COMPARE_CONTRAST_THEMES,
  COMPARE_ORDER_RATIONAL_NUMBERS,
  CONVERT_DECIMALS_FRACTIONS_PERCENTS,
  CONVERT_STANDARD_METRIC_UNITS,
  COMPREHENSION_WRITTEN_DIRECTIONS,
  GENERAL_ORIENTATION_HUMAN_ANATOMY,
  CELL_STRUCTURE_FUNCTION_ORGANIZATION,
  DESCRIBE_CHEMICAL_REACTIONS,
  GENETIC_MATERIAL_AND_PROTEIN_STRUCTURE,
  MICROORGANISMS_IN_DISEASE,
  BASIC_MACROMOLECULES,
  DISTINGUISH_FACT_AND_OPINION,
  ENDOCRINE_SYSTEM,
  EVALUATE_AN_ARGUMENT,
  EVALUATE_INTEGRATE_DATA_MULTIPLE_SOURCES,
  TABLES_CHARTS_GRAPHS_STATISTICS,
  EVALUATE_AUTHORS_POINT_OF_VIEW,
  EVALUATE_AUTHORS_PURPOSE,
  PHYSICAL_PROPERTIES_CHANGES_MATTER,
  RELATIONSHIP_BETWEEN_VARIABLES,
  GASTROINTESTINAL_SYSTEM,
  GENITOURINARY_SYSTEM,
  IDENTIFY_BIASES_AND_STEREOTYPES,
  IDENTIFY_INFORMATION_FROM_A_GRAPHIC,
  IDENTIFY_INFORMATION_PRINTED_COMMUNICATION,
  IDENTIFY_PRIMARY_SOURCES,
  TOPIC_MAIN_IDEA_SUPPORTING_DETAILS,
  IMMUNE_SYSTEM,
  INFER_LOGICAL_CONCLUSIONS,
  INTEGUMENTARY_SYSTEM,
  INTERPRET_EVENTS_SEQUENCE,
  INTERPRET_TABLES_CHARTS_GRAPHS,
  INTERPRET_WORDS_PHRASES_CONTEXT,
  LOCATE_SPECIFIC_INFORMATION,
  NEUROMUSCULAR_SYSTEM,
  ARITHMETIC_RATIONAL_NUMBERS,
  PREDICT_RELATIONSHIPS,
  RECOGNIZE_BASIC_ATOMIC_STRUCTURE,
  RECOGNIZE_TEXT_STRUCTURE,
  REPRODUCTIVE_SYSTEM,
  RESPIRATORY_SYSTEM,
  SKELETAL_SYSTEM,
  SOLVE_EQUATIONS_IN_ONE_VARIABLE,
  REAL_WORLD_PERCENT_PROBLEMS,
  PROPORTIONS_RATIOS_RATES,
  SUMMARIZE_MULTI_PARAGRAPH_TEXT,
  TRANSLATE_EXPRESSIONS_EQUATIONS_INEQUALITIES,
  PROPERTIES_OF_SOLUTIONS,
  BASIC_SCIENTIFIC_MEASUREMENTS_TOOLS,
  USE_DICTIONARY_AND_LIBRARY_ENTRIES,
  EVIDENCE_PREDICTIONS_INFERENCES_CONCLUSIONS,
];

export function getGuidedLesson(
  section: string,
  topic: string,
  slug: string,
): GuidedLesson | undefined {
  return GUIDED_LESSONS.find(
    (l) => l.section === section && l.topic === topic && l.slug === slug,
  );
}

export function guidedLessonCount(): number {
  return GUIDED_LESSONS.length;
}
