/**
 * Regenerates src/content/guided-lessons.ts from the files present in
 * src/content/guided-lessons/. Run after adding converted lessons:
 *
 *   npx tsx scripts/build-guided-registry.mts
 */
import { readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const lessonsDir = path.join(root, "../src/content/guided-lessons");
const registryPath = path.join(root, "../src/content/guided-lessons.ts");

async function main() {
  const files = readdirSync(lessonsDir)
    .filter((f) => f.endsWith(".ts"))
    .sort();

  const entries: { file: string; constName: string }[] = [];
  for (const f of files) {
    const mod: Record<string, unknown> = await import(path.join(lessonsDir, f));
    const ns = (mod.default && Object.keys(mod).length === 1 ? mod.default : mod) as Record<string, unknown>;
    const name = Object.entries(ns).find(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      ([, v]: [string, any]) => v && v.slug && v.sections,
    )?.[0];
    if (!name) throw new Error(`${f}: no GuidedLesson export found`);
    entries.push({ file: f.replace(/\.ts$/, ""), constName: name });
  }

  const imports = entries
    .map((e) => `import { ${e.constName} } from "./guided-lessons/${e.file}";`)
    .join("\n");
  const list = entries.map((e) => `  ${e.constName},`).join("\n");

  const out = `// AUTO-GENERATED by scripts/build-guided-registry.mts. Do not edit the
// list by hand; add lesson files to guided-lessons/ and re-run the script.
import type { GuidedLesson } from "./guided-lesson-types";
${imports}

/**
 * Registry of skills converted to the guided lesson format. Skills not listed
 * here fall back to the flat LessonContent renderer, so conversion ships one
 * skill at a time.
 */
const GUIDED_LESSONS: GuidedLesson[] = [
${list}
];

export function getGuidedLesson(
  section: string,
  topic: string,
  slug: string,
): GuidedLesson | undefined {
  return GUIDED_LESSONS.find(
    (l) => l.section === section && l.topic === topic && l.slug === slug,
  );
}

export function guidedLessonCount(): number {
  return GUIDED_LESSONS.length;
}
`;

  writeFileSync(registryPath, out);
  console.log(`registry: ${entries.length} lessons`);
}

main();
