/**
 * Assemble authored study lessons (scratchpad/lesson-*.json) into the typed
 * module src/content/lessons.ts, ordered to match the blueprint. Validates the
 * shape and that each topic maps to a known section/topic in skills.ts.
 *
 * Usage: tsx scripts/build-lessons.mts [--write]
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { SKILLS } from "../src/content/skills";

const SCRATCH =
  "/tmp/claude-1000/-home-vardan/daa678ad-173e-4625-9462-0f4b3c9f05ed/scratchpad";
const OUT = "src/content/lessons.ts";

const SECTION_ORDER = ["READING", "MATH", "SCIENCE", "ENGLISH"];
const topicOrder = SKILLS.map((s) => `${s.section}:${s.topic}`);
const known = new Set(topicOrder);

interface Lesson {
  section: string;
  topic: string;
  title: string;
  intro: string;
  sections: { heading: string; body: string }[];
}

const errors: string[] = [];
const lessons: Lesson[] = [];

for (const file of readdirSync(SCRATCH).filter((f) => f.startsWith("lesson-") && f.endsWith(".json"))) {
  let l: Lesson;
  try {
    l = JSON.parse(readFileSync(join(SCRATCH, file), "utf8"));
  } catch (e) {
    errors.push(`${file}: invalid JSON — ${(e as Error).message}`);
    continue;
  }
  const where = file;
  if (!SECTION_ORDER.includes(l.section)) errors.push(`${where}: bad section ${l.section}`);
  if (!known.has(`${l.section}:${l.topic}`)) errors.push(`${where}: unknown ${l.section}:${l.topic}`);
  if (!l.title?.trim()) errors.push(`${where}: missing title`);
  if (!l.intro?.trim()) errors.push(`${where}: missing intro`);
  if (!Array.isArray(l.sections) || l.sections.length < 3)
    errors.push(`${where}: needs >=3 sections`);
  else
    l.sections.forEach((s, i) => {
      if (!s.heading?.trim()) errors.push(`${where}[${i}]: missing heading`);
      if (!s.body?.trim() || s.body.trim().length < 30) errors.push(`${where}[${i}]: body too short`);
    });
  lessons.push(l);
}

lessons.sort(
  (a, b) =>
    topicOrder.indexOf(`${a.section}:${a.topic}`) - topicOrder.indexOf(`${b.section}:${b.topic}`),
);

console.log(`Lessons: ${lessons.length}  Errors: ${errors.length}`);
for (const l of lessons) console.log(`  ${l.section}/${l.topic}: "${l.title}" (${l.sections.length} sections)`);
for (const e of errors) console.log("  ERROR " + e);

// every blueprint topic should have a lesson
for (const key of topicOrder) {
  if (!lessons.some((l) => `${l.section}:${l.topic}` === key)) console.log("  MISSING lesson for " + key);
}

if (process.argv.includes("--write")) {
  if (errors.length) {
    console.error("Refusing to write: fix errors first.");
    process.exit(1);
  }
  const body = lessons
    .map((l) => "  " + JSON.stringify({ section: l.section, topic: l.topic, title: l.title, intro: l.intro, sections: l.sections }) + ",")
    .join("\n");
  const ts = `import type { Lesson } from "./lesson-types";\n\n// AUTO-GENERATED by scripts/build-lessons.mts. Do not edit by hand.\n// Original study lessons authored to the ATI TEAS 7 skill taxonomy (skills.ts).\nexport const LESSONS: Lesson[] = [\n${body}\n];\n\nexport function getLesson(section: string, topic: string): Lesson | undefined {\n  return LESSONS.find((l) => l.section === section && l.topic === topic);\n}\n`;
  writeFileSync(OUT, ts);
  console.log(`\nWrote ${lessons.length} lessons to ${OUT}`);
}
