/**
 * Assemble per-section quick-reference sheets (scratchpad/quickref-*.json) into
 * src/content/quick-reference.ts.  Usage: tsx scripts/build-quick-reference.mts [--write]
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const SCRATCH =
  "/tmp/claude-1000/-home-vardan/daa678ad-173e-4625-9462-0f4b3c9f05ed/scratchpad";
const OUT = "src/content/quick-reference.ts";
const SECTION_ORDER = ["READING", "MATH", "SCIENCE", "ENGLISH"];

interface QuickRef {
  section: string;
  title: string;
  groups: { heading: string; items: string[] }[];
}

const errors: string[] = [];
const refs: QuickRef[] = [];

for (const file of readdirSync(SCRATCH).filter((f) => f.startsWith("quickref-") && f.endsWith(".json"))) {
  let r: QuickRef;
  try {
    r = JSON.parse(readFileSync(join(SCRATCH, file), "utf8"));
  } catch (e) {
    errors.push(`${file}: invalid JSON — ${(e as Error).message}`);
    continue;
  }
  if (!SECTION_ORDER.includes(r.section)) errors.push(`${file}: bad section ${r.section}`);
  if (!r.title?.trim()) errors.push(`${file}: missing title`);
  if (!Array.isArray(r.groups) || r.groups.length < 2) errors.push(`${file}: needs >=2 groups`);
  else
    r.groups.forEach((g, i) => {
      if (!g.heading?.trim()) errors.push(`${file}.group[${i}]: missing heading`);
      if (!Array.isArray(g.items) || g.items.length < 1) errors.push(`${file}.group[${i}]: empty items`);
    });
  refs.push(r);
}

refs.sort((a, b) => SECTION_ORDER.indexOf(a.section) - SECTION_ORDER.indexOf(b.section));
console.log(`Quick-reference sheets: ${refs.length}  Errors: ${errors.length}`);
for (const r of refs) console.log(`  ${r.section}: "${r.title}" (${r.groups.length} groups)`);
for (const e of errors) console.log("  ERROR " + e);
for (const s of SECTION_ORDER) if (!refs.some((r) => r.section === s)) console.log("  MISSING " + s);

if (process.argv.includes("--write")) {
  if (errors.length) {
    console.error("Refusing to write: fix errors first.");
    process.exit(1);
  }
  const body = refs
    .map((r) => "  " + JSON.stringify({ section: r.section, title: r.title, groups: r.groups }) + ",")
    .join("\n");
  const ts = `import type { QuickReference } from "./quick-reference-types";\n\n// AUTO-GENERATED by scripts/build-quick-reference.mts. Do not edit by hand.\nexport const QUICK_REFERENCE: QuickReference[] = [\n${body}\n];\n\nexport function getQuickReference(section: string): QuickReference | undefined {\n  return QUICK_REFERENCE.find((r) => r.section === section);\n}\n`;
  writeFileSync(OUT, ts);
  console.log(`\nWrote ${refs.length} quick-reference sheets to ${OUT}`);
}
