/**
 * Assemble per-skill study cards (scratchpad/skill-*.json) into the typed
 * module src/content/skill-lessons.ts. Validates each card's skill against the
 * taxonomy in skills.ts and computes a URL slug.
 *
 * Usage: tsx scripts/build-skill-lessons.mts [--write]
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { SKILLS, slugifySkill } from "../src/content/skills";

const SCRATCH =
  "/tmp/claude-1000/-home-vardan/daa678ad-173e-4625-9462-0f4b3c9f05ed/scratchpad";
const OUT = "src/content/skill-lessons.ts";

const topicOrder = SKILLS.map((s) => `${s.section}:${s.topic}`);
const skillSet = new Map<string, Set<string>>();
for (const t of SKILLS) skillSet.set(`${t.section}:${t.topic}`, new Set(t.skills));

interface Card {
  section: string;
  topic: string;
  skill: string;
  summary: string;
  blocks: { heading: string; body: string }[];
}

const errors: string[] = [];
const cards: (Card & { slug: string })[] = [];
const seenSlug = new Set<string>();

for (const file of readdirSync(SCRATCH).filter((f) => f.startsWith("skill-") && f.endsWith(".json"))) {
  let arr: Card[];
  try {
    arr = JSON.parse(readFileSync(join(SCRATCH, file), "utf8"));
  } catch (e) {
    errors.push(`${file}: invalid JSON — ${(e as Error).message}`);
    continue;
  }
  arr.forEach((c, i) => {
    const where = `${file}[${i}]`;
    const known = skillSet.get(`${c.section}:${c.topic}`);
    if (!known) errors.push(`${where}: unknown ${c.section}:${c.topic}`);
    else if (!known.has(c.skill)) errors.push(`${where}: skill not in taxonomy — "${c.skill}"`);
    if (!c.summary?.trim()) errors.push(`${where}: missing summary`);
    if (!Array.isArray(c.blocks) || c.blocks.length < 1) errors.push(`${where}: needs blocks`);
    else
      c.blocks.forEach((b, j) => {
        if (!b.heading?.trim() || !b.body?.trim()) errors.push(`${where}.block[${j}]: empty`);
      });
    const slug = slugifySkill(c.skill);
    const slugKey = `${c.section}:${c.topic}:${slug}`;
    if (seenSlug.has(slugKey)) errors.push(`${where}: duplicate slug ${slug}`);
    seenSlug.add(slugKey);
    cards.push({ ...c, slug });
  });
}

cards.sort(
  (a, b) =>
    topicOrder.indexOf(`${a.section}:${a.topic}`) - topicOrder.indexOf(`${b.section}:${b.topic}`),
);

console.log(`Skill cards: ${cards.length}  Errors: ${errors.length}`);
const byTopic: Record<string, number> = {};
for (const c of cards) byTopic[`${c.section}/${c.topic}`] = (byTopic[`${c.section}/${c.topic}`] ?? 0) + 1;
for (const [k, n] of Object.entries(byTopic)) console.log(`  ${k.padEnd(34)} ${n}`);
for (const e of errors) console.log("  ERROR " + e);

// every skill in the taxonomy should have a card
for (const t of SKILLS)
  for (const skill of t.skills)
    if (!cards.some((c) => c.section === t.section && c.topic === t.topic && c.skill === skill))
      console.log(`  MISSING card: ${t.section}/${t.topic} :: ${skill}`);

if (process.argv.includes("--write")) {
  if (errors.length) {
    console.error("Refusing to write: fix errors first.");
    process.exit(1);
  }
  const body = cards
    .map((c) => "  " + JSON.stringify({ section: c.section, topic: c.topic, skill: c.skill, slug: c.slug, summary: c.summary, blocks: c.blocks }) + ",")
    .join("\n");
  const ts = `import type { SkillLesson } from "./skill-lesson-types";\n\n// AUTO-GENERATED by scripts/build-skill-lessons.mts. Do not edit by hand.\nexport const SKILL_LESSONS: SkillLesson[] = [\n${body}\n];\n\nexport function getSkillLesson(section: string, topic: string, slug: string): SkillLesson | undefined {\n  return SKILL_LESSONS.find((c) => c.section === section && c.topic === topic && c.slug === slug);\n}\n`;
  writeFileSync(OUT, ts);
  console.log(`\nWrote ${cards.length} skill cards to ${OUT}`);
}
